### ISSUE TITLE
Selecting from temporary table

### ISSUE THREAD

**Issue by iahmed9312** [sjh37/efreversepoco#831]
Dear,

I am trying to select from a temporary table in a stored procedure, but in the generated code it is giving me "cannot be created due to having out parameters, or is relying on the procedure result (int)" 

Here is an example stored procedure code:

```sql
CREATE PROCEDURE Test_SP2
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 1 Col1 INTO #temp;
    SELECT Col1 FROM #temp;
END;
```

Regards,
Ahmed

**Comment by sjh37** [comment]
This has been resolved and will be in the next release (tba). It now generates the following instead of the warning:

```cs
public int TestSp2()
{
    var procResultParam = new SqlParameter
    {
        ParameterName = "@procResult",
        SqlDbType = SqlDbType.Int,
        Direction = ParameterDirection.Output
    };

    Database.ExecuteSqlRaw("EXEC @procResult = [dbo].[Test_SP2] ", procResultParam);

    return (int)procResultParam.Value;
}
```

You can grab the [latest code from here](https://[raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude](https://raw.githubusercontent.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/master/EntityFramework.Reverse.POCO.Generator/EF.Reverse.POCO.v3.ttinclude)) and overwrite your `EF.Reverse.POCO.v3.ttinclude` file with it.

Any problems, let me know

**Comment by iahmed9312** [comment]
The warning has gone now but it is not returning the result correctly, it is returning "int" instead of the result table. 

What I am getting
`Task<int> Test_SP2Async(CancellationToken cancellationToken = default(CancellationToken));`

What i am expecting
`Task<List<Test_SP2ReturnModel>> Test_SP2Async(CancellationToken cancellationToken = default(CancellationToken));`
